name: psmqtt
version: 0.1.0
slug: psmqtt
description: Publishes host system metrics to MQTT using psmqtt.
url: https://github.com/mietzen/hassio-addons/tree/main/psmqtt
arch:
- aarch64
- amd64
startup: application
boot: auto
host_network: true
image: mietzen/hass-addon-psmqtt
init: false
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_clientid: psmqtt
  mqtt_qos: 0
  mqtt_retain: false
  mqtt_clean_session: true
  mqtt_reconnect_period_sec: 5
  mqtt_publish_topic_prefix: ""
  mqtt_ha_discovery_enabled: true
  mqtt_ha_discovery_topic: homeassistant
  mqtt_ha_discovery_device_name: ""
  logging_level: info
  schedule_yaml: |
    - cron: "every 5 minutes"
      tasks:
        - task: cpu_percent
          topic: "psmqtt/{hostname}/cpu/percent"
          ha_discovery:
            name: "CPU Usage"
            icon: "mdi:cpu-64-bit"
            unit_of_measurement: "%"
            state_class: "measurement"
        - task: virtual_memory
          params: [percent]
          topic: "psmqtt/{hostname}/memory/percent"
          ha_discovery:
            name: "Memory Usage"
            icon: "mdi:memory"
            unit_of_measurement: "%"
            state_class: "measurement"
        - task: disk_usage
          params: ["/", percent]
          topic: "psmqtt/{hostname}/disk/percent"
          ha_discovery:
            name: "Disk Usage"
            icon: "mdi:harddisk"
            unit_of_measurement: "%"
            state_class: "measurement"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: password?
  mqtt_clientid: str?
  mqtt_qos: "list(0|1|2)?"
  mqtt_retain: bool?
  mqtt_clean_session: bool?
  mqtt_reconnect_period_sec: int?
  mqtt_publish_topic_prefix: str?
  mqtt_ha_discovery_enabled: bool?
  mqtt_ha_discovery_topic: str?
  mqtt_ha_discovery_device_name: str?
  logging_level: "list(debug|info|warning|error)?"
  schedule_yaml: str
