name:  Auto-update-PRs
# If a pull request is already outdated when enabling auto-merge, manually click on the "Update branch" button a first time to avoid having to wait for another commit to land on the base branch for the pull request to be updated.
on:
  push:
    branches:
      - main

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: tibdex/auto-update@v2
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
